import {markdownTable} from 'markdown-table'
import {PullRequestContext} from './utils'

type ReportInput = {
  header: string
  intro: string
  body: string
  pullrequest: PullRequestContext
}

export default function generateReport(
  errors: string[],
  input: ReportInput
): string | null {
  if (!errors || errors.length < 1) {
    return null
  }

  const {header, intro, body, pullrequest} = input

  let report = intro

  report += `\n\n`
  report += `${markdownTable(
    [['', header], ...errors.map(err => [':no_entry_sign:', err])],
    {
      align: ['l', 'l'],
      padding: false
    }
  )}`
  report += `\n\n`
  report += body
  report += `\n\n`
  report +=
    '<p align="right">Generated by :zap: <a href="https://github.com/patrickkempff/prlint-action">PRLint</a> against {{commit}}</p>'

  report
    .replace(/{{title}}/g, pullrequest.title || 'null')
    .replace(/{{body}}/g, pullrequest.body || 'null')
    .replace(/{{branch}}/g, pullrequest.branch || 'null')
    .replace(/{{count}}/g, errors.length.toString())
    .replace(/{{commit}}/g, pullrequest.last_commit || 'null')

  return report
}
